version: '3.8'
services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  api:
    container_name: api
    build: ./server
    restart: always
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:postgres@db/db
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    depends_on:
      - db
  client:
    container_name: client
    build: ./client
    restart: always
    volumes:
      - ./client:/app
    ports:
      - '3000:3000'

  nginx:
    container_name: nginx
    image: nginx:1.21-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - client

  alembic:
    container_name: alembic
    build:
      context: ./server
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:postgres@db/db
      - ALEMBIC_CONFIG=/app/alembic.ini
    command: alembic upgrade head
    depends_on:
      - db

volumes:
  db:
    driver: local