"""Create cards table

Revision ID: 5f5a31350e09
Revises: 
Create Date: 2023-05-03 11:50:59.251717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker
from src.cards.models import Card


# revision identifiers, used by Alembic.
revision = '5f5a31350e09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('position'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('type')
    )
    # ### end Alembic commands ###

    Session = sessionmaker(bind=op.get_bind())
    session = Session()

    data = [
        {
            "type": "bank-draft",
            "title": "Bank Draft",
            "position": 0,
            "image": "/images/1.jpeg",
        },
        {
            "type": "bill-of-lading",
            "title": "Bill of Lading",
            "position": 1,
            "image": "/images/2.jpeg",
        },
        {
            "type": "invoice",
            "title": "Invoice",
            "position": 2,
            "image": "/images/3.jpeg",
        },
        {
            "type": "bank-draft-2",
            "title": "Bank Draft 2",
            "position": 3,
            "image": "/images/4.jpeg",
        },
        {
            "type": "bill-of-lading-2",
            "title": "Bill of Lading 2",
            "position": 4,
            "image": "/images/5.jpeg",
        },
    ]

    for item in data:
        card = Card(**item)
        session.add(card)

    session.commit()
    session.close()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
